on:
  push:
    branches:
      - master
      # - pipeline 

name: Auto Publish Doc
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-18.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.6' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified 

    - name: Instal Dependencie
      run: |
        pip3 install -r requirements.txt 
    - name: Build HTML
      run: |
        make html


    - name: Setup Python2
      uses: actions/setup-python@v2
      with:
        python-version: '2.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install BOS dependencies
      run: |
        wget https://sdk.bce.baidu.com/console-sdk/bce-cli-0.10.10.zip && unzip bce-cli-0.10.10.zip && cd bce-cli-0.10.10 && python setup.py install
     

    - name: Setup Docker
      run: |
        sudo apt install docker.io

    
    - name: build multi version
      run: |
        apt-get install make && make build-image && make release
        

    - name: Configure BOS Client
      run: |
        mkdir -p ~/.bce/ && bash  scripts/config_bos_client.sh > ~/.bce/credentials
      env:
        ACCESSKEYID: ${{ secrets.ACCESSKEYID }}
        ACCESSKEYSECRET: ${{ secrets.ACCESSKEYSECRET }}

        
    # - name: Upload to BOS
    #   run: |
    #     bce-cli-0.10.10/bce bos sync build bos:/xuperos-test/cms-store/xuperdoc

    - name: Upload to BOS
      run: |
        bce-cli-0.10.10/bce bos sync build/html bos:/opensource-xuperchain-doc/xuperdoc
